#! /bin/bash
#
# Author : Diego Martin Gardella [dgardella@gmail.com]
# Modified by Erling Ouweneel to switch OK and CRITICAL
#
# Desc : Plugin to verify if a file does not exist
#
#

PROGNAME=`basename $0`
PROGPATH=`echo $0 | sed -e 's,[\\/][^\\/][^\\/]*$,,'`

. $PROGPATH/utils.sh

if [ "$1" = "" ]
then
echo -e " Use : $PROGNAME -- Ex : $PROGNAME /etc/hosts \n "
exit $STATE_UNKNOWN
fi


if [ -f $1 ]
then
echo "CRITICAL - $1 : EXISTS :: `head -3 $1`" # shows the first three lines of the file
exit $STATE_CRITICAL
else
echo "OK : $1 Does NOT exists "
exit $STATE_OK
fi
