#!/bin/bash

while getopts "c:p:s:" option; do
    case "${option}" in 
    c)
        CADVISOR=${OPTARG}
        ;;
    p)
        PROJECT=${OPTARG}
        ;;
    s)
        SERVICES+=(${OPTARG})
        ;;
    *)
        echo "Bad option set"
        exit 3
        ;;
    esac
done

RES=""
RET=0

for exp in ${SERVICES[@]}; do
    FOUND=0
    if [ $(curl -s -o /dev/null -w "%{http_code}" http://${CADVISOR}/api/v1.3/docker/${PROJECT}_${exp}) == "200" ]; then 
        RES="$RES, $exp:OK"
        RET=$(($RET + 0))
    else
        RES="$RES, $exp:NOT OK"
        RET=$(($RET + 1))
    fi
done
if [ $RET -eq 0 ]; then
    PREFIX="OK"
else
    PREFIX="CRITICAL"
fi
echo ${PREFIX}${RES}
if [ $RET -eq 0 ]; then
    exit 0
fi
exit 2
